### ISSUE TITLE
Error after training model

### ISSUE THREAD

**Issue by vprima** [vertigo-io/vertigo-bot-factory#21]
L'entrainement se réalise correctement, mais j'ai l'erreur suivante qui est affichée :
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
![image](https://user-images.githubusercontent.com/82100873/119988735-b372b100-bfc6-11eb-8bde-f1fc1bc271eb.png)

Il me semble que l'erreur a lieu dans la fonction restart du fichier v-chatbot-dev.js

	restart: function (silent) {
				if (!silent) {
					this.systemMessage(this.$q.lang.vui.chatbot.restartMessage);
				}
				
				this.$http.post(this.botUrl, '{"sender":"' + this.convId + '","message":"/restart"}')
				.then(httpResponse => {
					this.startConversation("/start"); // lancement de la phrase d'accueil
				});
			},

Notre methode start est bien appelée dans le controller.

**Comment by mlaroche** [comment]
Can you please provide the content of the response to the request ?
From the message you have in the console it looks like there is an error on the server (code 500), do you have a stacktrace on the server side ?

**Comment by vprima** [comment]
This is what I get in the console : 

20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkCleanOldTrainings successfully in ( 5 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkSelectListChatbotNodeByCriteria successfully in ( 1 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkGetNextModelNumber successfully in ( 2 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkInsertTraining successfully in ( 23 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkGetAllTopicRelativeSmallTalkByBotId successfully in ( 3 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkExportSmallTalkRelativeTrainingSentence successfully in ( 3 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkExportUtterTextByBotId successfully in ( 2 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkExportResponseButtonByBotId successfully in ( 4 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkGetAllTopicRelativeScriptIntentByBotId successfully in ( 3 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkExportScriptIntentionRelativeTrainingSentence successfully in ( 3 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkGetScriptIntentionExportByBotId successfully in ( 2 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkGetBasicTopicByBotIdKtoCd successfully in ( 2 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkSelectListSmallTalkByCriteria successfully in ( 2 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkGetUtterTextByTopId successfully in ( 2 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkGetBasicTopicByBotIdKtoCd successfully in ( 3 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkSelectListSmallTalkByCriteria successfully in ( 3 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkGetUtterTextByTopId successfully in ( 2 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkGetBasicTopicByBotIdKtoCd successfully in ( 2 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkSelectListSmallTalkByCriteria successfully in ( 2 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkGetUtterTextByTopId successfully in ( 1 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  tasks       - Finish /execute/TkGetCurrentTrainingByBotId successfully in ( 5 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-1] INFO  page        - Finish /bot/{botId}/models/_train successfully in ( 97 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-8] INFO  page        - Finish /bot/{botId}/models/_talk successfully in ( 8 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-6] INFO  tasks       - Finish /execute/TkSelectListTrainingByCriteria successfully in ( 6 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-6] INFO  tasks       - Finish /execute/TkSelectListChatbotNodeByCriteria successfully in ( 5 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-6] INFO  page        - Finish /bot/{botId}/models/_refreshTrainings successfully in ( 26 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-9] INFO  webservices - Finish /Post//chatbot/start successfully in ( 2 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-5] INFO  page        - Finish /bot/{botId}/models/_start successfully in ( 20 ms) measures:{success=100.0} [] 
20210528 16:55:43 [http-nio-8080-exec-4] INFO  webservices - Finish /Put//chatbot/admin/model successfully in ( 380 ms) measures:{success=100.0} [] 
20210528 16:55:43 [ForkJoinPool.commonPool-worker-3] INFO  tasks       - Finish /execute/TkUpdateChatbotNode successfully in ( 4 ms) measures:{success=100.0} [] 
20210528 16:55:43 [ForkJoinPool.commonPool-worker-3] INFO  tasks       - Finish /execute/TkUpdateTraining successfully in ( 4 ms) measures:{success=100.0} [] 
20210528 16:55:44 [http-nio-8080-exec-2] INFO  tasks       - Finish /execute/TkSelectListChatbotNodeByCriteria successfully in ( 9 ms) measures:{success=100.0} [] 
20210528 16:55:44 [http-nio-8080-exec-2] INFO  tasks       - Finish /execute/TkSelectTrainingByUri successfully in ( 4 ms) measures:{success=100.0} [] 
20210528 16:55:44 [http-nio-8080-exec-2] INFO  page        - Finish /bot/{botId}/models/_refreshTrainer successfully in ( 28 ms) measures:{success=100.0} [] 
20210528 16:55:44 [http-nio-8080-exec-7] INFO  page        - Finish /bot/{botId}/models/_refreshTrainingInfo successfully in ( 20 ms) measures:{success=100.0} [] 
20210528 16:55:44 [http-nio-8080-exec-10] INFO  tasks       - Finish /execute/TkSelectListTrainingByCriteria successfully in ( 11 ms) measures:{success=100.0} [] 
20210528 16:55:44 [http-nio-8080-exec-10] INFO  tasks       - Finish /execute/TkSelectListChatbotNodeByCriteria successfully in ( 5 ms) measures:{success=100.0} [] 
20210528 16:55:44 [http-nio-8080-exec-10] INFO  page        - Finish /bot/{botId}/models/_refreshTrainings successfully in ( 37 ms) measures:{success=100.0} [] 

It's strange, because it says that /Post//chatbot/start and /bot/{botId}/models/_start were successful, but as I wrote before I get the following error in the chrome console : 

![image](https://user-images.githubusercontent.com/82100873/120003942-7f06f100-bfd6-11eb-90e2-d0c1c77e4af0.png)

**Comment by mlaroche** [comment]
Your logger configuration seams a little weird ;-) maybe you wan tweak it to have more detail!
Can you please provide the content of the response to the request ?

**Comment by vprima** [comment]
Hello
Here is my request : http://localhost:8080/vertigo-bot-executor/api/chatbot/start POST
Here is the response on my side : 

<!doctype html><html lang="fr"><head>
<title>État HTTP 404 – Non trouvé</title>
<style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head>
<body><h1>État HTTP 404 – Non trouvé</h1>
<hr class="line" />
<p><b>Type</b> Rapport d'état</p>
<p><b>message</b> La ressource demandée [&#47;vertigo-bot-executor&#47;api&#47;chatbot&#47;start] n&#39;est pas disponible</p>
<p><b>description</b> La ressource demandée n'est pas disponible.</p>
<hr class="line" />
<h3>Apache Tomcat/9.0.45</h3>
</body></html>

**Comment by vprima** [comment]
The issue was corrected, the javascript was not up to date with the new version.
